name: NodeJS deps + tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: cd typescript/ && npm i && npm i -g stryker-cli 
      
    - name: Run stryker
      run: cd typescript/ && stryker run
